### ISSUE TITLE
Discussion: deprecate configParser

### ISSUE THREAD

**Issue by Woile** [commitizen-tools/commitizen#55]
#### Goal
The idea is to deprecate configParser in favor of using only `toml` configuration.

#### Description

Right now is possible to have a `.cz`, `setup.cfg`, `.cz.cfg`. 
I think configParser is not flexible enough and hard to maintin. 
Because commitizen already installs toml, I think we can move from `.cz` to `.cz.toml` and we can deprecate `setup.cfg`, `.cz.cfg`.

#### Tasks

- [x] Remove from `init` command ini files options
- [ ] Clean documentation from `ini` confs
- [ ] Remove from code

**Comment by Lee-W** [comment]
My suggestion would be using the `toml` format but accept the name `.cz`, `.cz.tmol`.

**Comment by Woile** [comment]
so we'd use `toml` for everything. It's also a possibility.
This would be the options:
```
.cz
.cz.toml
pyproject.toml
```
and all of the would use `toml`, right?

**Comment by Lee-W** [comment]
Yep, that makes sense to me. I gonna implement #54 in `toml` only.

**Comment by Lee-W** [comment]
After reading TOML document, maybe we should not use `.cz`.

> TOML files should use the extension .toml.

Also, maybe we should add a deprecation warning for it?

**Comment by Woile** [comment]
Agreed, let's allow this files only then:

```
.cz.toml
pyproject.toml
```

And yes, we need to add a deprecation warning

**Comment by Woile** [comment]
Also: remove from `init` command those files

**Comment by Lee-W** [comment]
close by #230
